<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $companies = [
            'Freynet-Gagné',
            'Brenden Achtemiuk',
            'CDEM',
            'Centre de santé',
            'Editing Services',
            'FAJEF',
            'FLMM',
            'Kigaana Productions',
            'LMIC',
            'Magnify Digital',
            'Manito LFC 2 INC.',
            'Manitoba Metis Federation',
            'Manitoba Teachers\' Society',
            'MANSO',
            'NANB',
            'National Gallery of Canada',
            'Peaceful Ronin Media',
            'Print Studio One PO 27085',
            'Réseau Compassion Network',
            'Roberto Bocangel',
            'RTAM',
            'RWB',
            'Santé en français',
            'Tiber River',
            'Travel Manitoba',
            'Université de Saint-Boniface',
            'University of Manitoba',
            'Ville de Winnipeg',
            'MWEC',
            'WEM',
            'WEOC',
            'Winnipeg Arts Council',
            'Centre de Renouveau Aulneau',
            'CFEE',
            'Deposit Guarantee Corporation of Manitoba',
            'FortWhyte Alive',
            'ISED',
            'Jessica Meza Resillas',
            'Johnston Group',
            'Manitoba Housing',
            'Manitoba School Boards',
            'Matrix Group Publishing',
            'NNAS',
            'Patrick Lessard',
            'Peak of the Market',
            'Probe Research',
            'SFM',
            'Taro PR',
            'Wookey Films',
            'Alamos Gold Inc.',
            'Canadian Home Economics Fondation',
            'Conseil des arts',
            'Enjoy Creative',
            'Event Camp',
            'Livres Canada Books',
            'Lorraine Prefontaine (varia)',
            'MB School Boards',
            'TR PO 465390',
            'Wawanesa',
            'WSP',
            'Apprentissage Illimité',
            'Association de la Neurofibromatose du Québec',
            'Conseil des arts du Canada',
            'Creative Manitoba',
            'Fondation',
            'LRSD Indigenous Education Team',
            'Luiz Nunes',
            'Matrix Group Publish',
            'Alberta Education',
            'Assiniboine Park Conservancy',
            'Brodi Restaurants Ltd.',
            'Chronic Centre for Veterans',
            'FMRI',
            'Heatmaster',
            'Hôpital Général Saint-Boniface',
            'MBLL',
            'Pollard',
            'Richardson International',
            'Stantec',
            'Stories for Caregivers',
            'The Cover Guy',
            'University of Manitoba PO 468744',
            'Urban Shaman Contemporary Aboriginal Art',
            'Wearecinco',
            'Wilmar Ariza',
            'Winnipeg School Division',
            'Bureau du conseil Privé',
            'Canada Council for the Arts',
            'Manitoba School Boards Association',
            'Musée canadien Pour les Droits de la Personne',
            'Savoir Montfort',
            'SodaStream',
            'St.Amant',
            'UpHouse',
            'Alliance catholique canadienne de la santé',
            'Baltic Brothers',
            'Bounce Design',
            'Centre national d\'excellence sur la douleur chronique pour les vétérans canadiens',
            'EDAC',
            'G3 Canada Limited',
            'Guy Dumont',
            'Johnston group',
            'Manitoba Association of Optometrists',
            'Paula Isaak',
            'Rémi Courcelles',
            'Agriculture in the Classroom-Manitoba',
            'All Seniors Care Living Centres Inc',
            'Animal Health Canada',
            'Castle Health',
            'Eupraxia Training',
            'FCFM',
            'Heritage Winnipeg',
            'Manitoba child care association',
            'PADRAIG',
            'Phonique média',
            'pipikwan Pêhtâkwan',
            'PVLIP',
            'Bounce',
            'Chronic Pain Centre of Excellence',
            'Direct Focus',
            'LCTaylor',
            'Louisiana Department of Education',
            'Pembina Trails School Division',
            'Provincial Court of Saskatchewan',
            'Sapphire Springs Inc.',
            'Sophie Bissonnette',
            'Canadian Museum Human Rights PO 1029122',
            'Centre Scolaire Centre Nord',
            'MBLL - HR',
            'Mustafa Elmi',
            'Roadwest Pictures',
            'Shared Health MB',
            'ViewSource Media',
            'After Caregiving',
            'Génome Canada',
            'NCTR',
            'Urbanink',
            'Roll Focus',
            'Pascale Kihn',
            'George & Fay Yee Centre for Healthcare Innovation',
            'Sem Ltd.',
            'Phonique Média',
            'Great Plains Publishing',
            'PROJETS EN ATTENTE',
            'Louis Riel Institute',
            'On Screen Manitoba',
            'Mangrove',
            'Economic Development Winnipeg (Tourism Wpg & YES! WPG)',
            'Spadrole',
            'Université du Manitoba',
            'University of Manitoba',
        ];

        // Remove duplicates
        $uniqueCompanies = array_unique($companies);

        foreach ($uniqueCompanies as $companyName) {
            Company::firstOrCreate(['company_name' => $companyName]);
        }
    }
}
