export default [
  { heading: 'Forms & Tables' },
  {
    title: 'Form Elements',
    icon: { icon: 'bx-checkbox-checked' },
    action: 'read',
    subject: 'form-elements',
    children: [
      { title: 'Autocomplete', to: 'forms-autocomplete', action: 'read', subject: 'autocomplete' },
      { title: 'Checkbox', to: 'forms-checkbox', action: 'read', subject: 'checkbox' },
      { title: 'Combobox', to: 'forms-combobox', action: 'read', subject: 'combobox' },
      { title: 'Date Time Picker', to: 'forms-date-time-picker', action: 'read', subject: 'date-time-picker' },
      { title: 'Editors', to: 'forms-editors', action: 'read', subject: 'editors' },
      { title: 'File Input', to: 'forms-file-input', action: 'read', subject: 'file-input' },
      { title: 'Radio', to: 'forms-radio', action: 'read', subject: 'radio' },
      { title: 'Custom Input', to: 'forms-custom-input', action: 'read', subject: 'custom-input' },
      { title: 'Range Slider', to: 'forms-range-slider', action: 'read', subject: 'range-slider' },
      { title: 'Rating', to: 'forms-rating', action: 'read', subject: 'rating' },
      { title: 'Select', to: 'forms-select', action: 'read', subject: 'select' },
      { title: 'Slider', to: 'forms-slider', action: 'read', subject: 'slider' },
      { title: 'Switch', to: 'forms-switch', action: 'read', subject: 'switch' },
      { title: 'Textarea', to: 'forms-textarea', action: 'read', subject: 'textarea' },
      { title: 'Textfield', to: 'forms-textfield', action: 'read', subject: 'textfield' },
    ],
  },
  {
    title: 'Form Layouts',
    icon: { icon: 'bx-layout' },
    to: 'forms-form-layouts',
    action: 'read',
    subject: 'form-layouts',
  },
  {
    title: 'Form Wizard',
    icon: { icon: 'bx-git-merge' },
    action: 'read',
    subject: 'form-wizard',
    children: [
      {
        title: 'Numbered',
        to: 'forms-form-wizard-numbered',
        action: 'read',
        subject: 'numbered-wizard',
      },
      {
        title: 'Icons',
        to: 'forms-form-wizard-icons',
        action: 'read',
        subject: 'icons-wizard',
      },
    ],
  },
  {
    title: 'Form Validation',
    icon: { icon: 'bx-check' },
    to: 'forms-form-validation',
    action: 'read',
    subject: 'form-validation',
  },
  {
    title: 'Tables',
    icon: { icon: 'bx-table' },
    action: 'read',
    subject: 'tables',
    children: [
      {
        title: 'Simple Table',
        to: 'tables-simple-table',
        action: 'read',
        subject: 'simple-table',
      },
      {
        title: 'Data Table',
        to: 'tables-data-table',
        action: 'read',
        subject: 'data-table',
      },
    ],
  },
]
